# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cc/zkTransformer/3rd/hyrax-bls12-381

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cc/zkTransformer/3rd/hyrax-bls12-381

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(CMAKE_COMMAND) -E cmake_progress_start /home/cc/zkTransformer/3rd/hyrax-bls12-381/CMakeFiles /home/cc/zkTransformer/3rd/hyrax-bls12-381/3rd/mcl/CMakeFiles/progress.marks
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cc/zkTransformer/3rd/hyrax-bls12-381/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
3rd/mcl/CMakeFiles/mclbn384_256.dir/rule:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/CMakeFiles/mclbn384_256.dir/rule
.PHONY : 3rd/mcl/CMakeFiles/mclbn384_256.dir/rule

# Convenience name for target.
mclbn384_256: 3rd/mcl/CMakeFiles/mclbn384_256.dir/rule

.PHONY : mclbn384_256

# fast build rule for target.
mclbn384_256/fast:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384_256.dir/build.make 3rd/mcl/CMakeFiles/mclbn384_256.dir/build
.PHONY : mclbn384_256/fast

# Convenience name for target.
3rd/mcl/CMakeFiles/mclbn384.dir/rule:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/CMakeFiles/mclbn384.dir/rule
.PHONY : 3rd/mcl/CMakeFiles/mclbn384.dir/rule

# Convenience name for target.
mclbn384: 3rd/mcl/CMakeFiles/mclbn384.dir/rule

.PHONY : mclbn384

# fast build rule for target.
mclbn384/fast:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384.dir/build.make 3rd/mcl/CMakeFiles/mclbn384.dir/build
.PHONY : mclbn384/fast

# Convenience name for target.
3rd/mcl/CMakeFiles/mclbn256.dir/rule:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/CMakeFiles/mclbn256.dir/rule
.PHONY : 3rd/mcl/CMakeFiles/mclbn256.dir/rule

# Convenience name for target.
mclbn256: 3rd/mcl/CMakeFiles/mclbn256.dir/rule

.PHONY : mclbn256

# fast build rule for target.
mclbn256/fast:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn256.dir/build.make 3rd/mcl/CMakeFiles/mclbn256.dir/build
.PHONY : mclbn256/fast

# Convenience name for target.
3rd/mcl/CMakeFiles/mcl_st.dir/rule:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/CMakeFiles/mcl_st.dir/rule
.PHONY : 3rd/mcl/CMakeFiles/mcl_st.dir/rule

# Convenience name for target.
mcl_st: 3rd/mcl/CMakeFiles/mcl_st.dir/rule

.PHONY : mcl_st

# fast build rule for target.
mcl_st/fast:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl_st.dir/build.make 3rd/mcl/CMakeFiles/mcl_st.dir/build
.PHONY : mcl_st/fast

# Convenience name for target.
3rd/mcl/CMakeFiles/mcl.dir/rule:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f CMakeFiles/Makefile2 3rd/mcl/CMakeFiles/mcl.dir/rule
.PHONY : 3rd/mcl/CMakeFiles/mcl.dir/rule

# Convenience name for target.
mcl: 3rd/mcl/CMakeFiles/mcl.dir/rule

.PHONY : mcl

# fast build rule for target.
mcl/fast:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl.dir/build.make 3rd/mcl/CMakeFiles/mcl.dir/build
.PHONY : mcl/fast

src/asm/bint-x64-amd64.o: src/asm/bint-x64-amd64.S.o

.PHONY : src/asm/bint-x64-amd64.o

# target to build an object file
src/asm/bint-x64-amd64.S.o:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl_st.dir/build.make 3rd/mcl/CMakeFiles/mcl_st.dir/src/asm/bint-x64-amd64.S.o
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl.dir/build.make 3rd/mcl/CMakeFiles/mcl.dir/src/asm/bint-x64-amd64.S.o
.PHONY : src/asm/bint-x64-amd64.S.o

src/asm/x86-64.o: src/asm/x86-64.S.o

.PHONY : src/asm/x86-64.o

# target to build an object file
src/asm/x86-64.S.o:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl_st.dir/build.make 3rd/mcl/CMakeFiles/mcl_st.dir/src/asm/x86-64.S.o
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl.dir/build.make 3rd/mcl/CMakeFiles/mcl.dir/src/asm/x86-64.S.o
.PHONY : src/asm/x86-64.S.o

src/bn_c256.o: src/bn_c256.cpp.o

.PHONY : src/bn_c256.o

# target to build an object file
src/bn_c256.cpp.o:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn256.dir/build.make 3rd/mcl/CMakeFiles/mclbn256.dir/src/bn_c256.cpp.o
.PHONY : src/bn_c256.cpp.o

src/bn_c256.i: src/bn_c256.cpp.i

.PHONY : src/bn_c256.i

# target to preprocess a source file
src/bn_c256.cpp.i:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn256.dir/build.make 3rd/mcl/CMakeFiles/mclbn256.dir/src/bn_c256.cpp.i
.PHONY : src/bn_c256.cpp.i

src/bn_c256.s: src/bn_c256.cpp.s

.PHONY : src/bn_c256.s

# target to generate assembly for a file
src/bn_c256.cpp.s:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn256.dir/build.make 3rd/mcl/CMakeFiles/mclbn256.dir/src/bn_c256.cpp.s
.PHONY : src/bn_c256.cpp.s

src/bn_c384.o: src/bn_c384.cpp.o

.PHONY : src/bn_c384.o

# target to build an object file
src/bn_c384.cpp.o:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384.dir/build.make 3rd/mcl/CMakeFiles/mclbn384.dir/src/bn_c384.cpp.o
.PHONY : src/bn_c384.cpp.o

src/bn_c384.i: src/bn_c384.cpp.i

.PHONY : src/bn_c384.i

# target to preprocess a source file
src/bn_c384.cpp.i:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384.dir/build.make 3rd/mcl/CMakeFiles/mclbn384.dir/src/bn_c384.cpp.i
.PHONY : src/bn_c384.cpp.i

src/bn_c384.s: src/bn_c384.cpp.s

.PHONY : src/bn_c384.s

# target to generate assembly for a file
src/bn_c384.cpp.s:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384.dir/build.make 3rd/mcl/CMakeFiles/mclbn384.dir/src/bn_c384.cpp.s
.PHONY : src/bn_c384.cpp.s

src/bn_c384_256.o: src/bn_c384_256.cpp.o

.PHONY : src/bn_c384_256.o

# target to build an object file
src/bn_c384_256.cpp.o:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384_256.dir/build.make 3rd/mcl/CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.o
.PHONY : src/bn_c384_256.cpp.o

src/bn_c384_256.i: src/bn_c384_256.cpp.i

.PHONY : src/bn_c384_256.i

# target to preprocess a source file
src/bn_c384_256.cpp.i:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384_256.dir/build.make 3rd/mcl/CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.i
.PHONY : src/bn_c384_256.cpp.i

src/bn_c384_256.s: src/bn_c384_256.cpp.s

.PHONY : src/bn_c384_256.s

# target to generate assembly for a file
src/bn_c384_256.cpp.s:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384_256.dir/build.make 3rd/mcl/CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.s
.PHONY : src/bn_c384_256.cpp.s

src/fp.o: src/fp.cpp.o

.PHONY : src/fp.o

# target to build an object file
src/fp.cpp.o:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl_st.dir/build.make 3rd/mcl/CMakeFiles/mcl_st.dir/src/fp.cpp.o
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl.dir/build.make 3rd/mcl/CMakeFiles/mcl.dir/src/fp.cpp.o
.PHONY : src/fp.cpp.o

src/fp.i: src/fp.cpp.i

.PHONY : src/fp.i

# target to preprocess a source file
src/fp.cpp.i:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl_st.dir/build.make 3rd/mcl/CMakeFiles/mcl_st.dir/src/fp.cpp.i
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl.dir/build.make 3rd/mcl/CMakeFiles/mcl.dir/src/fp.cpp.i
.PHONY : src/fp.cpp.i

src/fp.s: src/fp.cpp.s

.PHONY : src/fp.s

# target to generate assembly for a file
src/fp.cpp.s:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl_st.dir/build.make 3rd/mcl/CMakeFiles/mcl_st.dir/src/fp.cpp.s
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(MAKE) -f 3rd/mcl/CMakeFiles/mcl.dir/build.make 3rd/mcl/CMakeFiles/mcl.dir/src/fp.cpp.s
.PHONY : src/fp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mclbn384_256"
	@echo "... install/local"
	@echo "... mclbn384"
	@echo "... mclbn256"
	@echo "... mcl_st"
	@echo "... mcl"
	@echo "... src/asm/bint-x64-amd64.o"
	@echo "... src/asm/x86-64.o"
	@echo "... src/bn_c256.o"
	@echo "... src/bn_c256.i"
	@echo "... src/bn_c256.s"
	@echo "... src/bn_c384.o"
	@echo "... src/bn_c384.i"
	@echo "... src/bn_c384.s"
	@echo "... src/bn_c384_256.o"
	@echo "... src/bn_c384_256.i"
	@echo "... src/bn_c384_256.s"
	@echo "... src/fp.o"
	@echo "... src/fp.i"
	@echo "... src/fp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/cc/zkTransformer/3rd/hyrax-bls12-381 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

