/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.mcl;

public class CipherText {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CipherText(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CipherText obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MclJNI.delete_CipherText(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String toStr() {
    return MclJNI.CipherText_toStr(swigCPtr, this);
  }

  public String toString() {
    return MclJNI.CipherText_toString(swigCPtr, this);
  }

  public void fromStr(String str) {
    MclJNI.CipherText_fromStr(swigCPtr, this, str);
  }

  public void add(CipherText c) {
    MclJNI.CipherText_add(swigCPtr, this, CipherText.getCPtr(c), c);
  }

  public void mul(int m) {
    MclJNI.CipherText_mul__SWIG_0(swigCPtr, this, m);
  }

  public void mul(String str) {
    MclJNI.CipherText_mul__SWIG_1(swigCPtr, this, str);
  }

  public CipherText() {
    this(MclJNI.new_CipherText(), true);
  }

}
