/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.mcl;

public class PrivateKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PrivateKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrivateKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MclElgamalJNI.delete_PrivateKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String toStr() {
    return MclElgamalJNI.PrivateKey_toStr(swigCPtr, this);
  }

  public String toString() {
    return MclElgamalJNI.PrivateKey_toString(swigCPtr, this);
  }

  public void fromStr(String str) {
    MclElgamalJNI.PrivateKey_fromStr(swigCPtr, this, str);
  }

  public void save(String fileName) {
    MclElgamalJNI.PrivateKey_save(swigCPtr, this, fileName);
  }

  public void load(String fileName) {
    MclElgamalJNI.PrivateKey_load(swigCPtr, this, fileName);
  }

  public void init() {
    MclElgamalJNI.PrivateKey_init(swigCPtr, this);
  }

  public PublicKey getPublicKey() {
    return new PublicKey(MclElgamalJNI.PrivateKey_getPublicKey(swigCPtr, this), true);
  }

  public int dec(CipherText c, SWIGTYPE_p_bool b) {
    return MclElgamalJNI.PrivateKey_dec__SWIG_0(swigCPtr, this, CipherText.getCPtr(c), c, SWIGTYPE_p_bool.getCPtr(b));
  }

  public int dec(CipherText c) {
    return MclElgamalJNI.PrivateKey_dec__SWIG_1(swigCPtr, this, CipherText.getCPtr(c), c);
  }

  public void setCache(int rangeMin, int rangeMax) {
    MclElgamalJNI.PrivateKey_setCache(swigCPtr, this, rangeMin, rangeMax);
  }

  public void clearCache() {
    MclElgamalJNI.PrivateKey_clearCache(swigCPtr, this);
  }

  public PrivateKey() {
    this(MclElgamalJNI.new_PrivateKey(), true);
  }

}
