/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.mcl;

public class PublicKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MclElgamalJNI.delete_PublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String toStr() {
    return MclElgamalJNI.PublicKey_toStr(swigCPtr, this);
  }

  public String toString() {
    return MclElgamalJNI.PublicKey_toString(swigCPtr, this);
  }

  public void fromStr(String str) {
    MclElgamalJNI.PublicKey_fromStr(swigCPtr, this, str);
  }

  public void save(String fileName) {
    MclElgamalJNI.PublicKey_save(swigCPtr, this, fileName);
  }

  public void load(String fileName) {
    MclElgamalJNI.PublicKey_load(swigCPtr, this, fileName);
  }

  public void enc(CipherText c, int m) {
    MclElgamalJNI.PublicKey_enc__SWIG_0(swigCPtr, this, CipherText.getCPtr(c), c, m);
  }

  public void enc(CipherText c, String str) {
    MclElgamalJNI.PublicKey_enc__SWIG_1(swigCPtr, this, CipherText.getCPtr(c), c, str);
  }

  public void rerandomize(CipherText c) {
    MclElgamalJNI.PublicKey_rerandomize(swigCPtr, this, CipherText.getCPtr(c), c);
  }

  public void add(CipherText c, int m) {
    MclElgamalJNI.PublicKey_add__SWIG_0(swigCPtr, this, CipherText.getCPtr(c), c, m);
  }

  public void add(CipherText c, String str) {
    MclElgamalJNI.PublicKey_add__SWIG_1(swigCPtr, this, CipherText.getCPtr(c), c, str);
  }

  public PublicKey() {
    this(MclElgamalJNI.new_PublicKey(), true);
  }

}
