// this code is generated by python3 src/gen_bint_header.py proto
#define MCL_BINT_MAX_BIT 544
#if MCL_BINT_ASM == 1
extern "C" MCL_DLL_API Unit mclb_add1(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<1>(Unit *z, const Unit *x, const Unit *y) { return mclb_add1(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub1(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<1>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub1(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF1(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<1>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF1(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF1(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<1>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF1(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add2(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<2>(Unit *z, const Unit *x, const Unit *y) { return mclb_add2(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub2(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<2>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub2(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF2(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<2>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF2(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF2(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<2>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF2(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add3(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<3>(Unit *z, const Unit *x, const Unit *y) { return mclb_add3(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub3(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<3>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub3(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF3(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<3>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF3(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF3(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<3>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF3(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add4(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<4>(Unit *z, const Unit *x, const Unit *y) { return mclb_add4(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub4(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<4>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub4(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF4(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<4>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF4(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF4(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<4>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF4(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add5(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<5>(Unit *z, const Unit *x, const Unit *y) { return mclb_add5(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub5(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<5>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub5(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF5(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<5>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF5(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF5(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<5>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF5(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add6(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<6>(Unit *z, const Unit *x, const Unit *y) { return mclb_add6(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub6(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<6>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub6(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF6(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<6>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF6(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF6(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<6>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF6(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add7(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<7>(Unit *z, const Unit *x, const Unit *y) { return mclb_add7(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub7(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<7>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub7(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF7(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<7>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF7(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF7(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<7>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF7(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add8(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<8>(Unit *z, const Unit *x, const Unit *y) { return mclb_add8(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub8(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<8>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub8(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF8(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<8>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF8(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF8(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<8>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF8(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add9(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<9>(Unit *z, const Unit *x, const Unit *y) { return mclb_add9(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub9(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<9>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub9(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF9(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<9>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF9(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF9(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<9>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF9(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add10(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<10>(Unit *z, const Unit *x, const Unit *y) { return mclb_add10(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub10(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<10>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub10(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF10(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<10>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF10(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF10(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<10>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF10(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add11(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<11>(Unit *z, const Unit *x, const Unit *y) { return mclb_add11(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub11(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<11>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub11(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF11(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<11>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF11(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF11(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<11>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF11(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add12(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<12>(Unit *z, const Unit *x, const Unit *y) { return mclb_add12(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub12(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<12>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub12(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF12(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<12>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF12(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF12(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<12>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF12(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add13(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<13>(Unit *z, const Unit *x, const Unit *y) { return mclb_add13(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub13(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<13>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub13(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF13(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<13>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF13(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF13(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<13>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF13(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add14(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<14>(Unit *z, const Unit *x, const Unit *y) { return mclb_add14(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub14(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<14>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub14(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF14(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<14>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF14(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF14(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<14>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF14(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add15(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<15>(Unit *z, const Unit *x, const Unit *y) { return mclb_add15(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub15(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<15>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub15(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF15(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<15>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF15(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF15(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<15>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF15(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add16(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<16>(Unit *z, const Unit *x, const Unit *y) { return mclb_add16(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub16(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<16>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub16(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF16(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<16>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF16(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF16(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<16>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF16(z, x, y); }
#if MCL_SIZEOF_UNIT == 4
extern "C" MCL_DLL_API Unit mclb_add17(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<17>(Unit *z, const Unit *x, const Unit *y) { return mclb_add17(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub17(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<17>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub17(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF17(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<17>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF17(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF17(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<17>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF17(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add18(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<18>(Unit *z, const Unit *x, const Unit *y) { return mclb_add18(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub18(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<18>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub18(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF18(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<18>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF18(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF18(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<18>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF18(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add19(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<19>(Unit *z, const Unit *x, const Unit *y) { return mclb_add19(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub19(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<19>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub19(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF19(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<19>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF19(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF19(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<19>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF19(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add20(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<20>(Unit *z, const Unit *x, const Unit *y) { return mclb_add20(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub20(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<20>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub20(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF20(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<20>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF20(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF20(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<20>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF20(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add21(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<21>(Unit *z, const Unit *x, const Unit *y) { return mclb_add21(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub21(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<21>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub21(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF21(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<21>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF21(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF21(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<21>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF21(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add22(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<22>(Unit *z, const Unit *x, const Unit *y) { return mclb_add22(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub22(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<22>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub22(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF22(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<22>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF22(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF22(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<22>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF22(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add23(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<23>(Unit *z, const Unit *x, const Unit *y) { return mclb_add23(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub23(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<23>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub23(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF23(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<23>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF23(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF23(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<23>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF23(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add24(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<24>(Unit *z, const Unit *x, const Unit *y) { return mclb_add24(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub24(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<24>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub24(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF24(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<24>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF24(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF24(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<24>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF24(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add25(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<25>(Unit *z, const Unit *x, const Unit *y) { return mclb_add25(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub25(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<25>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub25(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF25(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<25>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF25(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF25(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<25>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF25(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add26(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<26>(Unit *z, const Unit *x, const Unit *y) { return mclb_add26(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub26(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<26>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub26(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF26(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<26>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF26(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF26(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<26>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF26(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add27(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<27>(Unit *z, const Unit *x, const Unit *y) { return mclb_add27(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub27(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<27>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub27(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF27(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<27>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF27(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF27(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<27>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF27(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add28(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<28>(Unit *z, const Unit *x, const Unit *y) { return mclb_add28(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub28(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<28>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub28(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF28(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<28>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF28(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF28(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<28>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF28(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add29(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<29>(Unit *z, const Unit *x, const Unit *y) { return mclb_add29(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub29(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<29>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub29(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF29(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<29>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF29(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF29(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<29>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF29(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add30(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<30>(Unit *z, const Unit *x, const Unit *y) { return mclb_add30(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub30(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<30>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub30(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF30(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<30>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF30(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF30(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<30>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF30(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add31(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<31>(Unit *z, const Unit *x, const Unit *y) { return mclb_add31(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub31(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<31>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub31(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF31(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<31>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF31(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF31(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<31>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF31(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_add32(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit addT<32>(Unit *z, const Unit *x, const Unit *y) { return mclb_add32(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_sub32(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subT<32>(Unit *z, const Unit *x, const Unit *y) { return mclb_sub32(z, x, y); }
extern "C" MCL_DLL_API void mclb_addNF32(Unit *z, const Unit *x, const Unit *y);
template<> inline void addNFT<32>(Unit *z, const Unit *x, const Unit *y) { mclb_addNF32(z, x, y); }
extern "C" MCL_DLL_API Unit mclb_subNF32(Unit *z, const Unit *x, const Unit *y);
template<> inline Unit subNFT<32>(Unit *z, const Unit *x, const Unit *y) { return mclb_subNF32(z, x, y); }
#endif // #if MCL_SIZEOF_UNIT == 4
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit1;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit1(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<1>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit1(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd1;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd1(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<1>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd1(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul1;
#else
extern "C" MCL_DLL_API void mclb_mul1(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<1>(Unit *z, const Unit *x, const Unit *y) { mclb_mul1(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr1;
#else
extern "C" MCL_DLL_API void mclb_sqr1(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<1>(Unit *y, const Unit *x) { mclb_sqr1(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit2;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit2(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<2>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit2(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd2;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd2(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<2>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd2(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul2;
#else
extern "C" MCL_DLL_API void mclb_mul2(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<2>(Unit *z, const Unit *x, const Unit *y) { mclb_mul2(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr2;
#else
extern "C" MCL_DLL_API void mclb_sqr2(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<2>(Unit *y, const Unit *x) { mclb_sqr2(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit3;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit3(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<3>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit3(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd3;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd3(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<3>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd3(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul3;
#else
extern "C" MCL_DLL_API void mclb_mul3(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<3>(Unit *z, const Unit *x, const Unit *y) { mclb_mul3(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr3;
#else
extern "C" MCL_DLL_API void mclb_sqr3(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<3>(Unit *y, const Unit *x) { mclb_sqr3(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit4;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit4(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<4>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit4(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd4;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd4(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<4>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd4(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul4;
#else
extern "C" MCL_DLL_API void mclb_mul4(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<4>(Unit *z, const Unit *x, const Unit *y) { mclb_mul4(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr4;
#else
extern "C" MCL_DLL_API void mclb_sqr4(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<4>(Unit *y, const Unit *x) { mclb_sqr4(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit5;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit5(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<5>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit5(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd5;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd5(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<5>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd5(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul5;
#else
extern "C" MCL_DLL_API void mclb_mul5(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<5>(Unit *z, const Unit *x, const Unit *y) { mclb_mul5(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr5;
#else
extern "C" MCL_DLL_API void mclb_sqr5(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<5>(Unit *y, const Unit *x) { mclb_sqr5(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit6;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit6(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<6>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit6(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd6;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd6(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<6>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd6(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul6;
#else
extern "C" MCL_DLL_API void mclb_mul6(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<6>(Unit *z, const Unit *x, const Unit *y) { mclb_mul6(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr6;
#else
extern "C" MCL_DLL_API void mclb_sqr6(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<6>(Unit *y, const Unit *x) { mclb_sqr6(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit7;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit7(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<7>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit7(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd7;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd7(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<7>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd7(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul7;
#else
extern "C" MCL_DLL_API void mclb_mul7(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<7>(Unit *z, const Unit *x, const Unit *y) { mclb_mul7(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr7;
#else
extern "C" MCL_DLL_API void mclb_sqr7(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<7>(Unit *y, const Unit *x) { mclb_sqr7(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit8;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit8(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<8>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit8(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd8;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd8(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<8>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd8(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul8;
#else
extern "C" MCL_DLL_API void mclb_mul8(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<8>(Unit *z, const Unit *x, const Unit *y) { mclb_mul8(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr8;
#else
extern "C" MCL_DLL_API void mclb_sqr8(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<8>(Unit *y, const Unit *x) { mclb_sqr8(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit9;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit9(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<9>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit9(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd9;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd9(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<9>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd9(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul9;
#else
extern "C" MCL_DLL_API void mclb_mul9(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<9>(Unit *z, const Unit *x, const Unit *y) { mclb_mul9(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr9;
#else
extern "C" MCL_DLL_API void mclb_sqr9(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<9>(Unit *y, const Unit *x) { mclb_sqr9(y, x); }
#if MCL_SIZEOF_UNIT == 4
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit10;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit10(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<10>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit10(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd10;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd10(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<10>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd10(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul10;
#else
extern "C" MCL_DLL_API void mclb_mul10(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<10>(Unit *z, const Unit *x, const Unit *y) { mclb_mul10(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr10;
#else
extern "C" MCL_DLL_API void mclb_sqr10(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<10>(Unit *y, const Unit *x) { mclb_sqr10(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit11;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit11(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<11>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit11(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd11;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd11(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<11>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd11(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul11;
#else
extern "C" MCL_DLL_API void mclb_mul11(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<11>(Unit *z, const Unit *x, const Unit *y) { mclb_mul11(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr11;
#else
extern "C" MCL_DLL_API void mclb_sqr11(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<11>(Unit *y, const Unit *x) { mclb_sqr11(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit12;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit12(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<12>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit12(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd12;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd12(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<12>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd12(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul12;
#else
extern "C" MCL_DLL_API void mclb_mul12(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<12>(Unit *z, const Unit *x, const Unit *y) { mclb_mul12(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr12;
#else
extern "C" MCL_DLL_API void mclb_sqr12(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<12>(Unit *y, const Unit *x) { mclb_sqr12(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit13;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit13(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<13>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit13(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd13;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd13(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<13>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd13(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul13;
#else
extern "C" MCL_DLL_API void mclb_mul13(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<13>(Unit *z, const Unit *x, const Unit *y) { mclb_mul13(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr13;
#else
extern "C" MCL_DLL_API void mclb_sqr13(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<13>(Unit *y, const Unit *x) { mclb_sqr13(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit14;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit14(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<14>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit14(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd14;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd14(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<14>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd14(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul14;
#else
extern "C" MCL_DLL_API void mclb_mul14(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<14>(Unit *z, const Unit *x, const Unit *y) { mclb_mul14(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr14;
#else
extern "C" MCL_DLL_API void mclb_sqr14(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<14>(Unit *y, const Unit *x) { mclb_sqr14(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit15;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit15(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<15>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit15(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd15;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd15(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<15>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd15(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul15;
#else
extern "C" MCL_DLL_API void mclb_mul15(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<15>(Unit *z, const Unit *x, const Unit *y) { mclb_mul15(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr15;
#else
extern "C" MCL_DLL_API void mclb_sqr15(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<15>(Unit *y, const Unit *x) { mclb_sqr15(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit16;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit16(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<16>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit16(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd16;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd16(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<16>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd16(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul16;
#else
extern "C" MCL_DLL_API void mclb_mul16(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<16>(Unit *z, const Unit *x, const Unit *y) { mclb_mul16(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr16;
#else
extern "C" MCL_DLL_API void mclb_sqr16(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<16>(Unit *y, const Unit *x) { mclb_sqr16(y, x); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnit17;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnit17(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitT<17>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnit17(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API u_ppu mclb_mulUnitAdd17;
#else
extern "C" MCL_DLL_API Unit mclb_mulUnitAdd17(Unit *z, const Unit *x, Unit y);
#endif
template<> inline Unit mulUnitAddT<17>(Unit *z, const Unit *x, Unit y) { return mclb_mulUnitAdd17(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_ppp mclb_mul17;
#else
extern "C" MCL_DLL_API void mclb_mul17(Unit *z, const Unit *x, const Unit *y);
#endif
template<> inline void mulT<17>(Unit *z, const Unit *x, const Unit *y) { mclb_mul17(z, x, y); }
#if MCL_BINT_ASM_X64 == 1
extern "C" MCL_DLL_API void_pp mclb_sqr17;
#else
extern "C" MCL_DLL_API void mclb_sqr17(Unit *y, const Unit *x);
#endif
template<> inline void sqrT<17>(Unit *y, const Unit *x) { mclb_sqr17(y, x); }
#endif // #if MCL_SIZEOF_UNIT == 4
#endif // #if MCL_BINT_ASM == 1
#if MCL_SIZEOF_UNIT == 8
	#define MCL_BINT_ADD_N 16
	#define MCL_BINT_MUL_N 9
#else
	#define MCL_BINT_ADD_N 32
	#define MCL_BINT_MUL_N 17
#endif
u_ppp get_add(size_t n);
inline Unit addN(Unit *z, const Unit *x, const Unit *y, size_t n)
{
	return get_add(n)(z, x, y);
}
u_ppp get_sub(size_t n);
inline Unit subN(Unit *z, const Unit *x, const Unit *y, size_t n)
{
	return get_sub(n)(z, x, y);
}
void_ppp get_addNF(size_t n);
inline void addNFN(Unit *z, const Unit *x, const Unit *y, size_t n)
{
	return get_addNF(n)(z, x, y);
}
u_ppp get_subNF(size_t n);
inline Unit subNFN(Unit *z, const Unit *x, const Unit *y, size_t n)
{
	return get_subNF(n)(z, x, y);
}
u_ppu get_mulUnit(size_t n);
inline Unit mulUnitN(Unit *z, const Unit *x, Unit y, size_t n)
{
	return get_mulUnit(n)(z, x, y);
}
u_ppu get_mulUnitAdd(size_t n);
inline Unit mulUnitAddN(Unit *z, const Unit *x, Unit y, size_t n)
{
	return get_mulUnitAdd(n)(z, x, y);
}
void_ppp get_mul(size_t n);
inline void mulN(Unit *z, const Unit *x, const Unit *y, size_t n)
{
	return get_mul(n)(z, x, y);
}
void_pp get_sqr(size_t n);
inline void sqrN(Unit *y, const Unit *x, size_t n)
{
	return get_sqr(n)(y, x);
}
