/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.mcl;

public class G2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected G2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(G2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Bn256JNI.delete_G2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public G2() {
    this(Bn256JNI.new_G2__SWIG_0(), true);
  }

  public G2(G2 rhs) {
    this(Bn256JNI.new_G2__SWIG_1(G2.getCPtr(rhs), rhs), true);
  }

  public G2(String xa, String xb, String ya, String yb) {
    this(Bn256JNI.new_G2__SWIG_2(xa, xb, ya, yb), true);
  }

  public boolean equals(G2 rhs) {
    return Bn256JNI.G2_equals(swigCPtr, this, G2.getCPtr(rhs), rhs);
  }

  public void set(String xa, String xb, String ya, String yb) {
    Bn256JNI.G2_set(swigCPtr, this, xa, xb, ya, yb);
  }

  public void clear() {
    Bn256JNI.G2_clear(swigCPtr, this);
  }

  public void setStr(String str) {
    Bn256JNI.G2_setStr(swigCPtr, this, str);
  }

  public String toString() {
    return Bn256JNI.G2_toString(swigCPtr, this);
  }

}
