/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.mcl;

public class GT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Bn256JNI.delete_GT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GT() {
    this(Bn256JNI.new_GT__SWIG_0(), true);
  }

  public GT(GT rhs) {
    this(Bn256JNI.new_GT__SWIG_1(GT.getCPtr(rhs), rhs), true);
  }

  public boolean equals(GT rhs) {
    return Bn256JNI.GT_equals(swigCPtr, this, GT.getCPtr(rhs), rhs);
  }

  public void clear() {
    Bn256JNI.GT_clear(swigCPtr, this);
  }

  public void setStr(String str) {
    Bn256JNI.GT_setStr(swigCPtr, this, str);
  }

  public String toString() {
    return Bn256JNI.GT_toString(swigCPtr, this);
  }

}
