import sys
import argparse
import collections

arg_p3 = 'Unit *z, const Unit *x, const Unit *y'
arg_p2 = 'Unit *y, const Unit *x'
arg_p2u = 'Unit *z, const Unit *x, Unit y'
param_u3 = 'z, x, y'
param_u2 = 'y, x'

protoType = {
  ('Unit', arg_p3) : 'u_ppp',
  ('void', arg_p3) : 'void_ppp',
  ('void', arg_p2) : 'void_pp',
  ('Unit', arg_p2u) : 'u_ppu',
}

# N : max unit size for 32-bit unit, N64 : max unit size for 64-bit unit
FuncType = collections.namedtuple('FuncType', 'name, ret, args, cname, prams, N, N64')

# print 'Unit mclb_add1(Unit *z, const Unit *x, const Unit *y);'
FuncType.printProto = lambda self, i: print(f'{self.ret} {self.cname}{i}({self.args});')

FuncType.getProtoType = lambda self: protoType[(self.ret, self.args)]

def gen_func(name, ret, args, cname, params, i):
  print(f'{ret} {cname}{i}({args});')

def gen_prototype(out, e):
  (name, ret, args, _, params, N, N64) = e

  print(f'''{e.getProtoType()} get_{name}(size_t n)
{{
#if MCL_BINT_ASM == 1''')
  for i in range(1, N + 1):
    if i == N64 + 1:
      print('#if MCL_SIZEOF_UNIT == 4')
    print(f'\tif (n == {i}) return mclb_{name}{i};')
  print('#endif // MCL_SIZEOF_UNIT == 4')
  print('#else // MCL_BINT_ASM == 1')
  for i in range(1, N + 1):
    if i == N64 + 1:
      print('#if MCL_SIZEOF_UNIT == 4')
    print(f'\tif (n == {i}) return {name}T<{i}>;')
  print('''#endif // MCL_SIZEOF_UNIT == 4
#endif // MCL_BINT_ASM == 1
	assert(0); // n is out of range (see MCL_BINT_MUL_N in include/mcl/config.hpp)
	return 0;
}''')

def gen_table(tbl, N, N64):
  # extern "C" prototypes of the generated functions
  for i in range(1, N + 1):
    if i == N64 + 1:
      print('#if MCL_SIZEOF_UNIT == 4')
    for e in tbl:
      e.printProto(i)
  print('#endif // #if MCL_SIZEOF_UNIT == 4')

def main():
  parser = argparse.ArgumentParser(description='gen header')
  parser.add_argument('out', type=str)
  parser.add_argument('-n', type=int, default=6, help='max size of 64-bit Unit for mul/sqr (see MCL_BINT_MUL_N in include/mcl/config.hpp)')
  opt = parser.parse_args()
  if not opt.out in ['switch']:
    print('bad out', opt.out)
    sys.exit(1)
  # mul/sqr : N <= MCL_BINT_MUL_N
  mulN64 = opt.n
  mulN = mulN64 * 2
  # mulUnit/mulUnitAdd/add/sub/addNF/subNF : N <= MCL_BINT_MUL_N2 = 2 MCL_BINT_MUL_N
  addN64 = mulN64 * 2
  addN = addN64 * 2

  addTbl = list(map(lambda x: FuncType(*x), [
    ('add', 'Unit', arg_p3, 'mclb_add', param_u3, addN, addN64),
    ('sub', 'Unit', arg_p3, 'mclb_sub', param_u3, addN, addN64),
    ('addNF', 'void', arg_p3, 'mclb_addNF', param_u3, addN, addN64),
    ('subNF', 'Unit', arg_p3, 'mclb_subNF', param_u3, addN, addN64),
    ('mulUnit', 'Unit', arg_p2u, 'mclb_mulUnit', param_u3, addN, addN64),
    ('mulUnitAdd', 'Unit', arg_p2u, 'mclb_mulUnitAdd', param_u3, addN, addN64),
  ]))

  mulTbl = list(map(lambda x: FuncType(*x), [
    ('mul', 'void', arg_p3, 'mclb_mul', param_u3, mulN, mulN64),
    ('sqr', 'void', arg_p2, 'mclb_sqr', param_u2, mulN, mulN64),
  ]))

  print('// this code is generated by python3 src/gen_bint_header.py', opt.out, '-n', opt.n)
  print('#if MCL_BINT_ASM == 1')
  print('extern "C" {')
  gen_table(addTbl, addN, addN64)
  gen_table(mulTbl, mulN, mulN64)
  print('}')
  print('#endif // #if MCL_BINT_ASM == 1')

  for ft in addTbl + mulTbl:
    gen_prototype(opt.out, ft)

if __name__ == '__main__':
  main()
