import argparse
import primetbl

parser = argparse.ArgumentParser(description='generate src/llvm_proto.hpp')
parser.add_argument('-fpbit', type=int, default=384, help='MCL_FP_BIT given to src/gen.py (sizeof(Fp) of the Fp2 functions for the A_ slots)')
opt = parser.parse_args()

N32tbl = [6, 7, 8, 12, 16]
N64tbl = [3, 4, 6, 8]

def gen_get_ptr(t):
	name = t[0]
	retType = t[1]
	ret = t[2]
	args = t[3]
	print(f'static inline {retType} get_llvm_{name}(size_t n)')
	print('{')
	print('#ifdef MCL_USE_LLVM')
	print('	switch (n) {')
	print('	default: return 0;')
	print('#if MCL_SIZEOF_UNIT == 4')
	for i in N32tbl:
		print(f'	case {i}: return mcl_{name}{i}L;')
	print('#else')
	for i in N64tbl:
		print(f'	case {i}: return mcl_{name}{i}L;')
	print('#endif')
	print('	}')
	print('''#else
	(void)n;
	return 0;
#endif
}''')

def gen_proto(t):
	name = t[0]
	retType = t[1]
	ret = t[2]
	args = t[3]
	for i in set(N32tbl+N64tbl):
		print(f'{ret} mcl_{name}{i}L({args});')

def gen_sqr_mont_impl(suf, n):
	print(f'static inline void mcl_fp_sqrMont{suf}{n}L(Unit *z, const Unit *x, const Unit *p) {{ return mcl_fp_mont{suf}{n}L(z, x, x, p); }}')

def gen_sqr_mont(suf):
	print('#ifdef MCL_USE_LLVM')
	print('#if MCL_SIZEOF_UNIT == 4')
	for i in N32tbl:
		gen_sqr_mont_impl(suf, i)
	print('#else')
	for i in N64tbl:
		gen_sqr_mont_impl(suf, i)
	print('#endif')
	print('#endif')

void3u = 'Unit*, const Unit*, const Unit*'
void4u = 'Unit*, const Unit*, const Unit*, const Unit*'

void3uType = 'bint::void_ppp'
void4uType = 'bint::void_pppp'
tbl = [
	('fp_add', void4uType, 'void', void4u),
	('fp_sub', void4uType, 'void', void4u),
	('fp_addNF', void4uType, 'void', void4u),
	('fp_subNF', void4uType, 'void', void4u),
	('fp_mont', void4uType, 'void', void4u),
	('fp_montNF', void4uType, 'void', void4u),
	('fp_montRed', void3uType, 'void', void3u),
	('fp_montRedNF', void3uType, 'void', void3u),
	('fpDbl_add', void4uType, 'void', void4u),
	('fpDbl_sub', void4uType, 'void', void4u),
]

# the MCL_FP_BIT of the generation of src/base{32,64}.ll (the -fpbit of
# src/gen.py = the MCL_FP_BIT of the Makefile): sizeof(Fp) of the Fp2
# functions for the A_ slots (the position of the second component). fp.cpp
# rejects a build with a different MCL_FP_BIT by #error (regenerate by
# make update_all_asm MCL_FP_BIT=... and make header).
print(f'#define MCL_FP_BIT_LLVM {opt.fpbit}')
print('namespace mcl { namespace fp {')

print('extern "C" {')
for t in tbl:
	gen_proto(t)
print('void mcl_fp_mulNIST_P192L(Unit *, const Unit *, const Unit *, const Unit *);')
print('void mcl_fp_sqr_NIST_P192L(Unit *, const Unit *, const Unit *);')
print('void mcl_fpDbl_mod_NIST_P192L(Unit *, const Unit *, const Unit *);')
print('void mcl_fpDbl_mod_NIST_P521L(Unit *, const Unit *, const Unit *);')
print('}')

gen_sqr_mont('')
gen_sqr_mont('NF')

tbl.append(('fp_sqrMont', void3uType, 'void', void3u))
tbl.append(('fp_sqrMontNF', void3uType, 'void', void3u))

for t in tbl:
	gen_get_ptr(t)

# The A_ slots of Op (fp_addA_, ...) in the LLVM configurations without
# the x64 asm (MCL_DIRECT_CALL && !MCL_X64_ASM, see setLLVMCode of fp.cpp):
# (slot of Op, suffix of the function name, C argument list). Their types
# void2uA / void3uA (op.hpp) take p as the last argument there, i.e. void3u /
# void4u.
void2u = 'Unit*, const Unit*'
# Fp2 (sizeof(Fp) = MCL_FP_BIT_LLVM / 8): independent of u / xi_a
gen_fp2_tbl = [
	('fp2_addA_', 'add', void4u),
	('fp2_subA_', 'sub', void4u),
	('fp2_negA_', 'neg', void3u),
	('fp2_mul2A_', 'mul2_', void3u),
]
# per u (i^2 = -u)
gen_fp2_u_tbl = [
	('fp2_mulA_', 'mul', void4u),
	('fp2_sqrA_', 'sqr', void3u),
]
gen_fp2Dbl_u_tbl = [
	('fp2Dbl_mulPreA_', 'mulPre', void4u),
	('fp2Dbl_sqrPreA_', 'sqrPre', void3u),
]

# the p-generic functions (p as the last argument, rp = p[-1]) of N units
# generated by common.gen_generic_fp / gen_generic_fp2 (src/gen.py) for
# bit = 256 and 384 and the (u, xi_a) of the pairing curves of primetbl.py:
#   mcl_fp_{add,sub,mont,montRed}{NF}{N}L, mcl_fpDbl_{add,sub}{N}L (above),
#   mcl_fp_neg{N}L, mcl_fp_mul2_{N}L / mcl_fp_mul2NF{N}L, mcl_fp_sqr{N}L / mcl_fp_sqrNF{N}L,
#   mcl_fp2_{add,sub,neg}{N}L, mcl_fp2_mul2_{N}L,
#   mcl_fp2_{mul,sqr}_u{u}_{N}L, mcl_fp2Dbl_{mulPre,sqrPre}_u{u}_{N}L,
#   mcl_fp2_mul_xi_u{u}x{xi_a}_{N}L, mcl_fp2Dbl_mul_xi_u{u}x{xi_a}_{N}L
genN32tbl = [8, 12]
genN64tbl = [4, 6]
genParams = sorted({(cv.u, cv.xi_a) for cv in primetbl.curveTbl.values() if cv.u != 0})
genUs = sorted({u for (u, _) in genParams})

# the names of the Fp functions of N units: (slot, name) for isFullBit
def gen_fp_names(N, isFullBit):
	suf = f'{N}L'
	nf = '' if isFullBit else 'NF'
	return [
		('fp_addA_', f'mcl_fp_add{nf}{suf}'),
		('fp_subA_', f'mcl_fp_sub{nf}{suf}'),
		('fp_negA_', f'mcl_fp_neg{suf}'),
		('fp_mul2A_', f'mcl_fp_mul2{"_" if isFullBit else "NF"}{suf}'),
		('fp_mulA_', f'mcl_fp_mont{nf}{suf}'),
		('fp_sqrA_', f'mcl_fp_sqr{nf}{suf}'),
		('fpDbl_modA_', f'mcl_fp_montRed{nf}{suf}'),
		('fpDbl_addA_', f'mcl_fpDbl_add{suf}'),
		('fpDbl_subA_', f'mcl_fpDbl_sub{suf}'),
	]

def gen_generic_proto(Ntbl):
	for N in Ntbl:
		suf = f'{N}L'
		# the new Fp functions (the others are declared above)
		print(f'void mcl_fp_neg{suf}({void3u});')
		print(f'void mcl_fp_mul2_{suf}({void3u});')
		print(f'void mcl_fp_mul2NF{suf}({void3u});')
		print(f'void mcl_fp_sqr{suf}({void3u});')
		print(f'void mcl_fp_sqrNF{suf}({void3u});')
		for (slot, s, args) in gen_fp2_tbl:
			print(f'void mcl_fp2_{s}{suf}({args});')
		for u in genUs:
			for (slot, s, args) in gen_fp2_u_tbl:
				print(f'void mcl_fp2_{s}_u{u}_{suf}({args});')
			for (slot, s, args) in gen_fp2Dbl_u_tbl:
				print(f'void mcl_fp2Dbl_{s}_u{u}_{suf}({args});')
		for (u, xi_a) in genParams:
			print(f'void mcl_fp2_mul_xi_u{u}x{xi_a}_{suf}({void3u});')
			print(f'void mcl_fp2Dbl_mul_xi_u{u}x{xi_a}_{suf}({void3u});')

def gen_set_fp(Ntbl, indent):
	for N in Ntbl:
		print(f'{indent}case {N}:')
		for isFullBit in (True, False):
			print(f'{indent}	{"if (isFullBit)" if isFullBit else "else"} {{')
			for (slot, name) in gen_fp_names(N, isFullBit):
				print(f'{indent}		op.{slot} = {name};')
			print(f'{indent}	}}')
		print(f'{indent}	break;')

def gen_set_fp2(Ntbl, indent):
	for N in Ntbl:
		suf = f'{N}L'
		print(f'{indent}case {N}:')
		for (slot, s, args) in gen_fp2_tbl:
			print(f'{indent}	op.{slot} = mcl_fp2_{s}{suf};')
		for k, (u, xi_a) in enumerate(genParams):
			print(f'{indent}	{"if" if k == 0 else "} else if"} (u == {u} && xi_a == {xi_a}) {{')
			for (slot, s, args) in gen_fp2_u_tbl:
				print(f'{indent}		op.{slot} = mcl_fp2_{s}_u{u}_{suf};')
			for (slot, s, args) in gen_fp2Dbl_u_tbl:
				print(f'{indent}		op.{slot} = mcl_fp2Dbl_{s}_u{u}_{suf};')
			print(f'{indent}		op.fp2_mul_xiA_ = mcl_fp2_mul_xi_u{u}x{xi_a}_{suf};')
			print(f'{indent}		op.fp2Dbl_mul_xiA_ = mcl_fp2Dbl_mul_xi_u{u}x{xi_a}_{suf};')
		print(f'{indent}	}}')
		print(f'{indent}	break;')

print('#if defined(MCL_USE_LLVM) && !defined(MCL_WASM32) && !defined(MCL_X64_ASM)')
print('// the p-generic functions for the A_ slots (see common.gen_generic_fp / gen_generic_fp2 in src/gen.py)')
print('extern "C" {')
print('#if MCL_SIZEOF_UNIT == 4')
gen_generic_proto(genN32tbl)
print('#else')
gen_generic_proto(genN64tbl)
print('#endif')
print('}')
print('// set the A_ slots of Fp (and fpDbl_{mod,add,sub}A_) of op to the p-generic')
print('// functions of N units; false if N is not supported (then op is not changed)')
print('static inline bool set_llvm_fp(Op& op, size_t N, bool isFullBit)')
print('{')
print('	switch (N) {')
print('#if MCL_SIZEOF_UNIT == 4')
gen_set_fp(genN32tbl, '	')
print('#else')
gen_set_fp(genN64tbl, '	')
print('#endif')
print('	default: return false;')
print('	}')
print('	op.fp_mul = op.fp_mulA_; // used in toMont/fromMont')
print('	return true;')
print('}')
print('// set the Fp2 / Fp2Dbl A_ slots of op to the p-generic functions of N units')
print('// for Fp2 = Fp[i]/(i^2 + u) with xi = xi_a + i; false if (N, u, xi_a) is not')
print('// supported (then op is not changed). The caller checks sizeof(Fp) ==')
print('// MCL_FP_BIT_LLVM / 8, p not full bit and p < R/4.')
print('static inline bool set_llvm_fp2(Op& op, size_t N, int u, int xi_a)')
print('{')
cond = ' || '.join(f'(u == {u} && xi_a == {xi_a})' for (u, xi_a) in genParams)
print(f'	if (!({cond})) return false;')
print('	switch (N) {')
print('#if MCL_SIZEOF_UNIT == 4')
gen_set_fp2(genN32tbl, '	')
print('#else')
gen_set_fp2(genN64tbl, '	')
print('#endif')
print('	default: return false;')
print('	}')
print('	return true;')
print('}')
print('#endif')

print('}}')
