N32tbl = [6, 7, 8, 12, 16]
N64tbl = [3, 4, 6, 8]

def gen_get_ptr(t):
	name = t[0]
	retType = t[1]
	ret = t[2]
	args = t[3]
	print(f'static inline {retType} get_llvm_{name}(size_t n)')
	print('{')
	print('#ifdef MCL_USE_LLVM')
	print('	switch (n) {')
	print('	default: return 0;')
	print('#if MCL_SIZEOF_UNIT == 4')
	for i in N32tbl:
		print(f'	case {i}: return mcl_{name}{i}L;')
	print('#else')
	for i in N64tbl:
		print(f'	case {i}: return mcl_{name}{i}L;')
	print('#endif')
	print('	}')
	print('''#else
	(void)n;
	return 0;
#endif
}''')

def gen_proto(t):
	name = t[0]
	retType = t[1]
	ret = t[2]
	args = t[3]
	for i in set(N32tbl+N64tbl):
		print(f'{ret} mcl_{name}{i}L({args});')

def gen_sqr_mont_impl(suf, n):
	print(f'static inline void mcl_fp_sqrMont{suf}{n}L(Unit *z, const Unit *x, const Unit *p) {{ return mcl_fp_mont{suf}{n}L(z, x, x, p); }}')

def gen_sqr_mont(suf):
	print('#ifdef MCL_USE_LLVM')
	print('#if MCL_SIZEOF_UNIT == 4')
	for i in N32tbl:
		gen_sqr_mont_impl(suf, i)
	print('#else')
	for i in N64tbl:
		gen_sqr_mont_impl(suf, i)
	print('#endif')
	print('#endif')

void3u = 'Unit*, const Unit*, const Unit*'
void4u = 'Unit*, const Unit*, const Unit*, const Unit*'

void3uType = 'bint::void_ppp'
void4uType = 'bint::void_pppp'
tbl = [
	('fp_add', void4uType, 'void', void4u),
	('fp_sub', void4uType, 'void', void4u),
	('fp_addNF', void4uType, 'void', void4u),
	('fp_subNF', void4uType, 'void', void4u),
	('fp_mont', void4uType, 'void', void4u),
	('fp_montNF', void4uType, 'void', void4u),
	('fp_montRed', void3uType, 'void', void3u),
	('fp_montRedNF', void3uType, 'void', void3u),
	('fpDbl_add', void4uType, 'void', void4u),
	('fpDbl_sub', void4uType, 'void', void4u),
]

print('namespace mcl { namespace fp {')

print('extern "C" {')
for t in tbl:
	gen_proto(t)
print('void mcl_fp_mulNIST_P192L(Unit *, const Unit *, const Unit *, const Unit *);')
print('void mcl_fp_sqr_NIST_P192L(Unit *, const Unit *, const Unit *);')
print('void mcl_fpDbl_mod_NIST_P192L(Unit *, const Unit *, const Unit *);')
print('void mcl_fpDbl_mod_NIST_P521L(Unit *, const Unit *, const Unit *);')
print('}')

gen_sqr_mont('')
gen_sqr_mont('NF')

tbl.append(('fp_sqrMont', void3uType, 'void', void3u))
tbl.append(('fp_sqrMontNF', void3uType, 'void', void3u))

for t in tbl:
	gen_get_ptr(t)

# p-fixed functions of BLS12-381 (curve type 5) generated by common.gen_fixed
# (src/gen.py): the same ABI as the Xbyak functions (no p argument), so they
# are registered to the A_ slots of Op (see setLLVMFixedCode in fp.cpp).
# (slot of Op, suffix of the function name, C argument list)
# The function name is the prefix ('mcl_c5_fp_', 'mcl_c5_fr_') with the last
# '_' replaced by the suffix: 'Dbl_mod' -> mcl_c5_fpDbl_mod, '2_add' -> mcl_c5_fp2_add.
void2u = 'Unit*, const Unit*'
c5_fp_tbl = [
	('fp_addA_', '_add', void3u),
	('fp_subA_', '_sub', void3u),
	('fp_negA_', '_neg', void2u),
	('fp_mul2A_', '_mul2', void2u),
	('fp_mulA_', '_mul', void3u),
	('fp_sqrA_', '_sqr', void2u),
	('fpDbl_modA_', 'Dbl_mod', void2u),
]
# only for Fp (hasFp2 of gen_fixed)
c5_fpDbl_tbl = [
	('fpDbl_addA_', 'Dbl_add', void3u),
	('fpDbl_subA_', 'Dbl_sub', void3u),
]
# only for Fp with Fp2 = Fp[i]/(i^2 + 1), xi = 1 + i and sizeof(Fp) = 48
c5_fp2_tbl = [
	('fp2_addA_', '2_add', void3u),
	('fp2_subA_', '2_sub', void3u),
	('fp2_negA_', '2_neg', void2u),
	('fp2_mul2A_', '2_mul2', void2u),
	('fp2_mulA_', '2_mul', void3u),
	('fp2_sqrA_', '2_sqr', void2u),
	('fp2_mul_xiA_', '2_mul_xi', void2u),
]

def c5_name(pre, suf):
	return pre[:-1] + suf

def gen_c5_proto(pre, tbls):
	print(f'extern Unit {pre}p[];')
	for tbl in tbls:
		for (slot, suf, args) in tbl:
			print(f'void {c5_name(pre, suf)}({args});')

# set the slots of tbls to the functions with the prefix pre
def gen_c5_set(name, pre, tbls, setFpMul):
	print(f'static inline void {name}(Op& op)')
	print('{')
	for tbl in tbls:
		for (slot, suf, args) in tbl:
			print(f'	op.{slot} = {c5_name(pre, suf)};')
	if setFpMul:
		print('	op.fp_mul = fp::func_ptr_cast<void4u>(op.fp_mulA_); // used in toMont/fromMont')
	print('}')

print('#if defined(MCL_USE_LLVM) && !defined(MCL_WASM32)')
print('// p-fixed functions of BLS12-381 (see common.gen_fixed in src/gen.py); the Xbyak ABI (no p argument)')
print('extern "C" {')
gen_c5_proto('mcl_c5_fp_', [c5_fp_tbl, c5_fpDbl_tbl, c5_fp2_tbl])
gen_c5_proto('mcl_c5_fr_', [c5_fp_tbl])
print('}')
print('// register them to op (the caller checks that op.p is the prime of the functions)')
gen_c5_set('set_llvm_c5_fp', 'mcl_c5_fp_', [c5_fp_tbl, c5_fpDbl_tbl], True)
print('// Fp2 of BLS12-381 : xi_a == 1, u == 1 and sizeof(Fp) == 48 (the offset of the second component is fixed)')
gen_c5_set('set_llvm_c5_fp2', 'mcl_c5_fp_', [c5_fp2_tbl], False)
gen_c5_set('set_llvm_c5_fr', 'mcl_c5_fr_', [c5_fp_tbl], True)
print('#endif')

print('}}')

