// generated by src/gen_msm_para.py
static const uint64_t g_mask = 0xfffffffffffff;
static const uint64_t g_vmask_[] = { g_mask, g_mask, g_mask, g_mask, g_mask, g_mask, g_mask, g_mask, };
static const uint64_t g_rp = 0x3fffcfffcfffd;
static const uint64_t g_vrp_[] = { g_rp, g_rp, g_rp, g_rp, g_rp, g_rp, g_rp, g_rp, };

struct G {
	static const Vec& vmask() { return *(const Vec*)g_vmask_; }
	static const Vec& vrp() { return *(const Vec*)g_vrp_; }
};

