#if 0
p=0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab
W=52
N=8
mask=0xfffffffffffff
R=0x14c8ee06ef23c24a25ff6eb6fdd4230a6723e5f0ade53b2ee82efd4228b540fea96f7d65766c8fe444f6480ea8e9b9af
R2=0x87462075d7450726698e5907ad91f53480a4a188311a84d7104659032646160ec71f13afbba7ca31a2a5bf4cb89af51
rp=0x3fffcfffcfffd
m64to52=0x411cd9d20d7e399594137cc89a9b0bb206f497dfcafb872b2b91b9dc1f5b1e97784894e27525bc342b7fde37dba9366
#endif
// generated by src/gen_msm_para.py
static const uint64_t g_mask = 0xfffffffffffff;
static const CYBOZU_ALIGN(64) uint64_t g_vmask_[] = { 0xfffffffffffff, 0xfffffffffffff, 0xfffffffffffff, 0xfffffffffffff, 0xfffffffffffff, 0xfffffffffffff, 0xfffffffffffff, 0xfffffffffffff, };
static const CYBOZU_ALIGN(64) uint64_t g_vrp_[] = { 0x3fffcfffcfffd, 0x3fffcfffcfffd, 0x3fffcfffcfffd, 0x3fffcfffcfffd, 0x3fffcfffcfffd, 0x3fffcfffcfffd, 0x3fffcfffcfffd, 0x3fffcfffcfffd, };
static const CYBOZU_ALIGN(64) uint64_t g_vpN_[] = {
0xeffffffffaaab, 0xeffffffffaaab, 0xeffffffffaaab, 0xeffffffffaaab, 0xeffffffffaaab, 0xeffffffffaaab, 0xeffffffffaaab, 0xeffffffffaaab,
0xfeb153ffffb9f, 0xfeb153ffffb9f, 0xfeb153ffffb9f, 0xfeb153ffffb9f, 0xfeb153ffffb9f, 0xfeb153ffffb9f, 0xfeb153ffffb9f, 0xfeb153ffffb9f,
0x6b0f6241eabff, 0x6b0f6241eabff, 0x6b0f6241eabff, 0x6b0f6241eabff, 0x6b0f6241eabff, 0x6b0f6241eabff, 0x6b0f6241eabff, 0x6b0f6241eabff,
0x12bf6730d2a0f, 0x12bf6730d2a0f, 0x12bf6730d2a0f, 0x12bf6730d2a0f, 0x12bf6730d2a0f, 0x12bf6730d2a0f, 0x12bf6730d2a0f, 0x12bf6730d2a0f,
0x764774b84f385, 0x764774b84f385, 0x764774b84f385, 0x764774b84f385, 0x764774b84f385, 0x764774b84f385, 0x764774b84f385, 0x764774b84f385,
0x1ba7b6434bacd, 0x1ba7b6434bacd, 0x1ba7b6434bacd, 0x1ba7b6434bacd, 0x1ba7b6434bacd, 0x1ba7b6434bacd, 0x1ba7b6434bacd, 0x1ba7b6434bacd,
0x1ea397fe69a4b, 0x1ea397fe69a4b, 0x1ea397fe69a4b, 0x1ea397fe69a4b, 0x1ea397fe69a4b, 0x1ea397fe69a4b, 0x1ea397fe69a4b, 0x1ea397fe69a4b,
0x1a011, 0x1a011, 0x1a011, 0x1a011, 0x1a011, 0x1a011, 0x1a011, 0x1a011,
};
static const CYBOZU_ALIGN(64) uint64_t g_offset_[] = { 0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8 };

struct G {
	static const Vec& vmask() { return *(const Vec*)g_vmask_; }
	static const Vec& vrp() { return *(const Vec*)g_vrp_; }
	static const Vec* vpN() { return (const Vec*)g_vpN_; }
	static const Vec& offset() { return *(const Vec*)g_offset_; }
};

