// generated by src/gen_msm_para.py
static const uint64_t g_mask = 0xfffffffffffff;
static const CYBOZU_ALIGN(64) uint64_t g_vmask_[] = { g_mask, g_mask, g_mask, g_mask, g_mask, g_mask, g_mask, g_mask, };
static const uint64_t g_rp = 0x3fffcfffcfffd;
static const CYBOZU_ALIGN(64) uint64_t g_vrp_[] = { g_rp, g_rp, g_rp, g_rp, g_rp, g_rp, g_rp, g_rp, };
static const uint64_t g_p0 = 0xeffffffffaaab;
static const uint64_t g_p1 = 0xfeb153ffffb9f;
static const uint64_t g_p2 = 0x6b0f6241eabff;
static const uint64_t g_p3 = 0x12bf6730d2a0f;
static const uint64_t g_p4 = 0x764774b84f385;
static const uint64_t g_p5 = 0x1ba7b6434bacd;
static const uint64_t g_p6 = 0x1ea397fe69a4b;
static const uint64_t g_p7 = 0x1a011;
static const CYBOZU_ALIGN(64) uint64_t g_vpN_[] = {
	g_p0, g_p0, g_p0, g_p0, g_p0, g_p0, g_p0, g_p0,
	g_p1, g_p1, g_p1, g_p1, g_p1, g_p1, g_p1, g_p1,
	g_p2, g_p2, g_p2, g_p2, g_p2, g_p2, g_p2, g_p2,
	g_p3, g_p3, g_p3, g_p3, g_p3, g_p3, g_p3, g_p3,
	g_p4, g_p4, g_p4, g_p4, g_p4, g_p4, g_p4, g_p4,
	g_p5, g_p5, g_p5, g_p5, g_p5, g_p5, g_p5, g_p5,
	g_p6, g_p6, g_p6, g_p6, g_p6, g_p6, g_p6, g_p6,
	g_p7, g_p7, g_p7, g_p7, g_p7, g_p7, g_p7, g_p7,
};

struct G {
	static const Vec& vmask() { return *(const Vec*)g_vmask_; }
	static const Vec& vrp() { return *(const Vec*)g_vrp_; }
	static const Vec* vpN() { return (const Vec*)g_vpN_; }
};

